version: '3.8'
services:
  api_backend:
    container_name: api_backend
    image: api_backend
    build:
      context: .
    ports:
      - ${APP_PORT}:3000
    env_file:
      - .env
    depends_on:
      - api_db
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

  api_db:
    container_name: api_db
    hostname: postgres
    image: 'postgres:13'
    restart: always
    ports:
      - '${APP_DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - api_db:/var/lib/postgresql/data

volumes:
  api_db: {}
